name: Serverless Deployement

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "17.x"
              #install serverless
            - name: Install Serverless Framework
              run: npm install -g serverless
              #install node modules
            - name: Install NPM dependencies
              run: npm ci
              # Install poetry action
            - name: Install Poetry Action
              uses: snok/install-poetry@v1.3.1
              # Test if fleece[cli] is installed and is working
            - name: Test fleece cli working?
              if:  ${{ success() }}
              run: |
                poetry install
                source $(poetry env info --path)/bin/activate
                fleece run --help
                fleece run -u ${{ secrets.RS_USERNAME }} -k ${{ secrets.RS_API_KEY }} -c ./environments.yml -e dev "sls deploy --verbose"